### ISSUE TITLE
Java application fails to start on Wayland due to X11 display issues

### ISSUE THREAD

**Issue by sjneves** [hneemann/Digital#1351]
# Description:
I am experiencing an issue when trying to run a Java application on a Wayland environment using XWayland. The application fails to find an X11 display and throws a HeadlessException, even though the XWayland compatibility layer is active.

# Environment:

**Operating System**: Fedora (version 40)
**Java Version**: OpenJDK 17
**Desktop Environment**: GNOME (version 46)

# Steps to Reproduce:

Start a Wayland session (GNOME on Wayland).
Ensure that XWayland is installed (xorg-x11-server-Xwayland).
Set the DISPLAY variable manually to :0 or :1 using:

```bash
export DISPLAY=:0
```
Try to run the Java application:

```bash
java -jar Digital.jar
```
# Expected Behavior:
The Java application should start correctly using the XWayland display.

# Actual Behavior:
The application fails to start and throws the following error:

```bash

./Digital.sh 
java.awt.HeadlessException: 
No X11 DISPLAY variable was set,
or no headful library support was found,
but this program performed an operation which requires it,

	at java.desktop/java.awt.GraphicsEnvironment.checkHeadless(GraphicsEnvironment.java:164)
	at java.desktop/java.awt.Window.<init>(Window.java:553)
	at java.desktop/java.awt.Frame.<init>(Frame.java:428)
	at java.desktop/javax.swing.JFrame.<init>(JFrame.java:224)
	at de.neemann.digital.gui.Main.<init>(Main.java:165)
	at de.neemann.digital.gui.Main.<init>(Main.java:93)
	at de.neemann.digital.gui.Main$MainBuilder.build(Main.java:2334)
	at de.neemann.digital.gui.Main.lambda$main$26(Main.java:2208)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:318)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:773)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:720)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:714)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:400)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:87)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:742)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
[AWT-EventQueue-0] INFO de.neemann.digital.gui.DigitalUncaughtExceptionHandler - uncaught exception log written to /home/------/Digital_2024-10-26_13-12-09.log
```

# Additional Information:

I have tried setting the `GDK_BACKEND=x11` and using `_JAVA_AWT_WM_NONREPARENTING=1`, but the issue persists.
The DISPLAY environment variable points to :0 or :1, but the error remains.
Running other X11 applications through XWayland works without issues.

**Comment by sjneves** [comment]
# Solution

I'm add 
```bash
export JAVA_TOOL_OPTIONS='-Djava.awt.headless=false'
```
to `Digital.sh`.
